name: Deploy identeco
description: Deploys identeco on AWS
inputs:
  stage:
    description: Stage to deploy (dev, prod, test, ...)
    required: true
    default: prod
  aws-access-key-id:
    description: AWS access key ID
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
runs:
  using: composite
  steps:
    - run: npm ci
      shell: bash

    - name: Remove profile from serverless.yml
      uses: mikefarah/yq@master
      with:
        cmd: yq -i 'del(.provider.profile)' serverless.yml

    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy --stage ci
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}

    - name: rotate keys
      uses: serverless/github-action@v3
      with:
        args: invoke --stage ci -f rotateKeys
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
