name: Deploy identeco

on:
  push:
    branches:
      - dev-0.1.3-alpha

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploy identeco on AWS
        uses: ./.github/workflows/deploy
        with:
          stage: prod
