name: Deploy identeco

on:
  push:
    branches:
      - dev-0.1.3-alpha

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      #- name: Use Node.js ${{ matrix.node-version }}
      #  uses: actions/setup-node@v1
      #  with:
      #    node-version: ${{ matrix.node-version }}

      - name: Deploy identeco on AWS
        id: deploy_action
        uses: ./.github/workflows/deploy
        with:
          stage: prod
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: |
          echo "--- API Endpoint:" ${{ steps.deploy_action.outputs.api-endpoint }}
          echo "--- API Region:" ${{ steps.deploy_action.outputs.aws-region }}
          python --version
          export IDENTECO_API_ENDPOINT=${{ steps.deploy_action.outputs.api-endpoint }}
          pip install -r test/requirements.txt
          python test/apitest.py
        shell: bash
